version: '3.9'

services:
  backend:
    build: .
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - POSTGRES_DB=blogdb
      - POSTGRES_USER=bloguser
      - POSTGRES_PASSWORD=blogpass
      - DB_HOST=db
      - DB_PORT=5432

    container_name: django-api
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - .env

  db:
    image: postgres:15
    container_name: blog_db
    restart: always
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: blogpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: